version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily

- package-ecosystem: github-actions
  directory: /v1
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: /v2
  schedule:
    interval: daily
