version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: "monday"
    time: "05:00"
    timezone: "Europe/Amsterdam"

- package-ecosystem: docker
  directory: /v1
  schedule:
    interval: weekly
    day: "monday"
    time: "05:00"
    timezone: "Europe/Amsterdam"
- package-ecosystem: docker
  directory: /v2
  schedule:
    interval: weekly
    day: "monday"
    time: "05:00"
    timezone: "Europe/Amsterdam"
