name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  build:
    # Required by gcloud auth
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Major version
        run: |
          MAJOR_VERSION=$(echo $GITHUB_REF | grep -oP '^refs/tags/v\K[0-9]+')
          if [[ "${MAJOR_VERSION}" == "1" ]]; then
            echo "LATEST=true" >> $GITHUB_ENV
          else
            echo "LATEST=false" >> $GITHUB_ENV
          fi
          echo "MAJOR_VERSION=v$MAJOR_VERSION" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gcr.io/instruqt/cloud-client
          # We mark container latest for v1 images.
          flavor: |
            latest=${{ env.LATEST }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GH_GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GH_GCLOUD_SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: ${{ env.MAJOR_VERSION }}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Github release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
